apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\jrami\Desktop\final-arqui\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: app2
  name: app2
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    io.kompose.service: app2
status:
  loadBalancer: {}
