apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\jrami\Desktop\final-arqui\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: app2
  name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\jrami\Desktop\final-arqui\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: app2
    spec:
      containers:
        - image: app2
          name: app2
          ports:
            - containerPort: 5001
          resources: {}
      restartPolicy: Always
status: {}
