version: '3.7'

services:
  mydb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=examen
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
  app1:
    build:
      context: .
      dockerfile: app1.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - HOST=192.168.1.87
      - PORT=5432
      - DATABASE=examen
      - USER=admin
      - PASSWORD=admin
  app2:
    build:
      context: .
      dockerfile: app2.Dockerfile
    ports:
      - "5001:5001"

