---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: snoopylord/final-arqui_app1
          ports:
            - containerPort: 5000
          env:
            - name: HOST
              value: '192.168.1.87'
            - name: PORT
              value: '5432'
            - name: DATABASE
              value: 'examen'
            - name: USER
              value: 'admin'
            - name: PASSWORD
              value: 'admin'
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: app1
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: snoopylord/final-arqui_app2
          ports:
            - containerPort: 5001

---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: app2
  type: LoadBalancer

  