apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\jrami\Desktop\final-arqui\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mydb
  name: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mydb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\jrami\Desktop\final-arqui\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: mydb
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: examen
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_USER
              value: admin
          image: postgres
          name: mydb
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: mydb-claim0
      restartPolicy: Always
      volumes:
        - name: mydb-claim0
          persistentVolumeClaim:
            claimName: mydb-claim0
status: {}
